#makefile for 1.03 pathfinding
all: 327_assignment1.03 rlg327 heap

327_assignment1.03: 327_assignment1.03.c
	gcc 327_assignment1.03.c -o 327_assignment1.03
rlg327: rlg327.c rlg327.h
	gcc rlg327.c -o rlg327
heap: heap.c heap.h
	gcc heap.c -o heap
clean:
	rm -f 327_assignment1.03 rlg327 heap
