# makefile for assignment 1.02. includes the assignment, and shaeffer's dungeon creator code
327_assignment1.02: 327_assignment1.02.c
	  	gcc 327_assignment1.02.c -o 327_assignment1.02
rlg327: rlg327.c
	gcc rlg327.c -o rlg327
clean:
	rm -f 327_assignment1.02 rgl327
